# lab2_service - dockerfile

FROM python:3.11-slim

WORKDIR /app

# db_config + generator + зависимости
COPY lab_shared/ .
RUN pip install --no-cache-dir -r requirements.txt

# Код сервиса
COPY lab2_service/app/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]