# lab1_service - dockerfile

FROM python:3.11-slim

WORKDIR /app

COPY lab1_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY lab_shared/ .
COPY lab1_service/app/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]